### ISSUE TITLE
定时执行不能实现

### ISSUE THREAD

**Issue by Onionfish2** [magojohnji/KernelSU_Action_template#1]
![Screenshot_20231003-204703_Chrome](https://github.com/magojohnji/KernelSU_Action_template/assets/123535045/8b7fab1f-09a4-43db-b0e4-af4e9d91b94d)
如题，麻烦解答一下谢谢。设置的每周 1，3，5 运行，可是到相应时间并没有运行且 release。望解答，谢谢！

**Comment by magojohnji** [comment]
对于自动运行，可能是 README.md 中的示例有问题，可以修改一下引号。自动运行工作流是 GitHub Actions 的特性，本项目只是使用了 GitHub 提供的方法，详见 [GitHub Docs](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)，下面是正确示范：
``` yaml
on:
  schedule:
    - cron: '30 5 * * 1,3'
    - cron: '30 5 * * 2,4'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Not on Monday or Wednesday
        if: github.event.schedule != '30 5 * * 1,3'
        run: echo "This step will be skipped on Monday and Wednesday"
```
如果解决问题可以回复一下


对于 release，可以修改 build-kernel.yml 的最后部分：去掉 
```yaml
 if: github.event.inputs.release == 'true' 
```
不过如此，Release 事件将无条件执行，Run Workflow 的 Release 复选框将名存实亡。也许将来有判断运行方式的方法出现，可以更好的解决问题，但目前没有。

PS：我将会对这个项目进行大改造，在 Workflows 中使用 Matrix，配置文件选择 Json，来使项目更易用，也许对这些问题有所帮助
